//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public string MaHD { get; set; }
        public string MaPhong { get; set; }
        public Nullable<float> GiamGia { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
