//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUEPHONG
    {
        public string MaPhieu { get; set; }
        public string MaKH { get; set; }
        public string MaPhong { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
