//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI_SD
    {
        public string MaPhong { get; set; }
        public string MaTB { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
